anguage: node_js
node_js:
  - "12"
sudo: true

addons:
  chrome: stable

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - yarn lint
  - ng test --watch false --browsers ChromeHeadless
  - ng build --prod